framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Activation du support de session (défaut : stockage fichiers)
    session:

        handler_id: null
        cookie_lifetime: 7200        # durée de vie du cookie (en secondes)
        gc_maxlifetime: 7200         # durée de vie des données de session côté serveur
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

    property_info:
        enabled: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
