security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # assets & profiler restent libres
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Autorise TOUTES les requêtes GET de ces routes à sortir du firewall
        public_get:
            pattern: ^/(login|inscription|info|offres|commande)$
            methods: [GET]
            security: false

        # API panier reste libre
        cart_api:
            pattern: ^/api/cart
            security: false

        # Tout le reste passe ici

        main:
            pattern: ^/
            provider: app_user_provider
            lazy: true

            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                enable_csrf: true

            logout:
                path:   app_logout
                target: app_login
                invalidate_session: true

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: false

    access_control:
        # checkout et admin protégés
        - { path: ^/checkout, roles: ROLE_USER }
        - { path: ^/admin,    roles: ROLE_ADMIN }
        - { path: ^/profil, roles: ROLE_USER }