app = "studijo2024"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [processes]
    web = "php -S 0.0.0.0:8000 -t public"
    worker = "php bin/console messenger:consume async"
