

parameters:
    locale: 'fr'

services:
    
    _defaults:
        autowire: true      
        autoconfigure: true 
        public: false       


    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']


    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection'
            - '../src/Entity'
            - '../src/Kernel.php'
            - '../src/Tests'
    
    Endroid\QrCode\Builder\Builder:
        autowire: true
        public: false

    Endroid\QrCode\Builder\BuilderInterface:
        alias: Endroid\QrCode\Builder\Builder